-- ============================================================
-- DRPlatform 数据库初始化脚本
-- 本地: 127.0.0.1:3306 root/123456
-- Linux: 192.168.88.88:3306 root/123456
-- 使用: mysql -h 127.0.0.1 -P 3306 -u root -p123456 < db/init.sql
-- ============================================================

CREATE DATABASE IF NOT EXISTS DRPlatform DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS geo_source  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS geo_target  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS biz_source  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE DATABASE IF NOT EXISTS biz_target  DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

-- -------------------- 管控元数据库 --------------------
USE DRPlatform;

CREATE TABLE IF NOT EXISTS sync_progress (
    ID                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    SOURCE_IP           VARCHAR(45)  NOT NULL,
    SOURCE_DB_NAME      VARCHAR(64)  NOT NULL,
    TARGET_IP           VARCHAR(45)  NOT NULL,
    TARGET_DB_NAME      VARCHAR(64)  NOT NULL,
    STATE               TINYINT      NOT NULL DEFAULT 0 COMMENT '0-失效 1-全量 2-同步中 3-中止',
    SYNC_START_TIME     DATETIME     DEFAULT NULL,
    SOURCE_BINLOG_FILE  VARCHAR(255) DEFAULT NULL,
    SOURCE_BINLOG_TIME  DATETIME     DEFAULT NULL,
    SYNC_BINLOG_FILE    VARCHAR(255) DEFAULT NULL,
    SYNC_BINLOG_TIME    DATETIME     DEFAULT NULL,
    DEVIATION_TIMES     BIGINT       DEFAULT NULL,
    DEVIATION_STATUS    TINYINT      DEFAULT NULL COMMENT '1-正常 2-异常',
    SUSPENSION_REASON   VARCHAR(512) DEFAULT NULL,
    PROCESSING_METHOD   VARCHAR(512) DEFAULT NULL,
    CREATE_TIME         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY IDX_SOURCE_IP_DB (SOURCE_IP, SOURCE_DB_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS dbha_switch_status (
    ID                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    VIRTUAL_IP          VARCHAR(45)  NOT NULL,
    OLD_MAIN_IP         VARCHAR(45)  DEFAULT NULL,
    OLD_STANDBY_IP      VARCHAR(45)  DEFAULT NULL,
    MAIN_IP             VARCHAR(45)  NOT NULL,
    STANDBY_IP          VARCHAR(45)  NOT NULL,
    SWITCH_TIME         DATETIME     DEFAULT NULL,
    SOURCE_DB_NAME      VARCHAR(64)  NOT NULL,
    SOURCE_BINLOG_FILE  VARCHAR(255) DEFAULT NULL,
    SOURCE_BINLOG_POS   BIGINT       DEFAULT NULL,
    CREATE_TIME         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY IDX_VIRTUAL_IP_DB (VIRTUAL_IP, SOURCE_DB_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS source_latest_binlog_info (
    ID                  BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    SOURCE_IP           VARCHAR(45)  NOT NULL,
    SOURCE_DB_NAME      VARCHAR(64)  NOT NULL,
    SOURCE_BINLOG_FILE  VARCHAR(255) NOT NULL,
    SOURCE_BINLOG_TIME  DATETIME     NOT NULL,
    SOURCE_BINLOG_POS   BIGINT       NOT NULL,
    CREATE_TIME         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY IDX_SOURCE_IP_DB (SOURCE_IP, SOURCE_DB_NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS sync_restart_task (
    ID           BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    SOURCE_HOST  VARCHAR(45) NOT NULL,
    SOURCE_DB    VARCHAR(64) NOT NULL,
    TARGET_HOST  VARCHAR(45) NOT NULL,
    TARGET_DB    VARCHAR(64) NOT NULL,
    STATUS       TINYINT     DEFAULT 0 COMMENT '0-待处理 1-处理中 2-成功 3-失败',
    ERROR_MSG    VARCHAR(1024) DEFAULT NULL,
    CREATE_TIME  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME  DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY IDX_UNIQUE_KEY (SOURCE_HOST, SOURCE_DB, TARGET_HOST, TARGET_DB)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -------------------- 后台管理用户 --------------------
CREATE TABLE IF NOT EXISTS sys_user (
    ID             BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    USERNAME       VARCHAR(64)  NOT NULL,
    PASSWORD_HASH  VARCHAR(128) NOT NULL COMMENT 'salt:sha256',
    SALT           VARCHAR(64)  NOT NULL,
    CREATE_TIME    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME    DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (ID),
    UNIQUE KEY IDX_USERNAME (USERNAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -------------------- 示例业务库（生产中心） --------------------
USE geo_source;

CREATE TABLE IF NOT EXISTS t_order (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_no    VARCHAR(64)  NOT NULL,
    user_id     BIGINT       NOT NULL,
    amount      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    status      TINYINT      NOT NULL DEFAULT 0,
    remark      VARCHAR(255) DEFAULT NULL,
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_user (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username    VARCHAR(64)  NOT NULL,
    age         INT          NOT NULL DEFAULT 0,
    email       VARCHAR(128) DEFAULT NULL,
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -------------------- 示例业务库（灾备中心，结构与源一致） --------------------
USE geo_target;

CREATE TABLE IF NOT EXISTS t_order (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    order_no    VARCHAR(64)  NOT NULL,
    user_id     BIGINT       NOT NULL,
    amount      DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    status      TINYINT      NOT NULL DEFAULT 0,
    remark      VARCHAR(255) DEFAULT NULL,
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_order_no (order_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t_user (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    username    VARCHAR(64)  NOT NULL,
    age         INT          NOT NULL DEFAULT 0,
    email       VARCHAR(128) DEFAULT NULL,
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_username (username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- -------------------- 第二个业务库对（多库同步演示：生产中心 biz_source -> 灾备中心 biz_target） --------------------
USE biz_source;

CREATE TABLE IF NOT EXISTS t_customer (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name        VARCHAR(64)  NOT NULL,
    phone       VARCHAR(32)  DEFAULT NULL,
    balance     DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

USE biz_target;

CREATE TABLE IF NOT EXISTS t_customer (
    id          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    name        VARCHAR(64)  NOT NULL,
    phone       VARCHAR(32)  DEFAULT NULL,
    balance     DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    create_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uk_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
